// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagementSystem.Db.Data;

#nullable disable

namespace ProductManagementSystem.Db.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714062038_AddMoreSeedProducts")]
    partial class AddMoreSeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductManagementSystem.Db.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Smartphones, Laptops, and Accessories",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kitchenware, TVs, and Home electronics",
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Apparel, Shoes, and Accessories",
                            Name = "Fashion"
                        });
                });

            modelBuilder.Entity("ProductManagementSystem.Db.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Apple iPhone 15 Pro 128GB, Natural Titanium",
                            ImageUrl = "/images/iphone15.jpg",
                            Name = "iPhone 15 Pro",
                            Price = 35000.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Apple MacBook Air 13-inch M3, 8GB RAM, 256GB SSD",
                            ImageUrl = "/images/macbook.jpg",
                            Name = "MacBook Air M3",
                            Price = 42000.00m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Samsung 55-inch Crystal UHD 4K Smart TV",
                            ImageUrl = "/images/tv.jpg",
                            Name = "Smart TV 55\"",
                            Price = 15900.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Automatic Espresso Machine with Milk Frother",
                            ImageUrl = "/images/coffeemaker.jpg",
                            Name = "Coffee Maker",
                            Price = 4500.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Lightweight breathable sports shoes for men and women",
                            ImageUrl = "/images/shoes.jpg",
                            Name = "Running Shoes",
                            Price = 2200.00m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Apple iPad Air 11-inch M2, 128GB Wi-Fi, Space Gray",
                            ImageUrl = "/images/ipad.jpg",
                            Name = "iPad Air M2",
                            Price = 23900.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Portable waterproof wireless speaker with deep bass",
                            ImageUrl = "/images/speaker.jpg",
                            Name = "Bluetooth Speaker",
                            Price = 1890.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "RGB backlit hot-swappable mechanical gaming keyboard",
                            ImageUrl = "/images/keyboard.jpg",
                            Name = "Mechanical Keyboard",
                            Price = 3200.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Lightweight ergonomic rechargeable gaming mouse",
                            ImageUrl = "/images/mouse.jpg",
                            Name = "Wireless Gaming Mouse",
                            Price = 2490.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Digital hot air fryer 4.5L with preset cooking modes",
                            ImageUrl = "/images/airfryer.jpg",
                            Name = "Air Fryer",
                            Price = 3590.00m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Double-wall stainless steel rapid boil electric kettle 1.7L",
                            ImageUrl = "/images/kettle.jpg",
                            Name = "Electric Kettle",
                            Price = 1290.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "High-speed mini bullet blender for smoothies and shakes",
                            ImageUrl = "/images/blender.jpg",
                            Name = "Personal Blender",
                            Price = 1590.00m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Non-slip eco-friendly exercise mat with carrying strap",
                            ImageUrl = "/images/yogamat.jpg",
                            Name = "Yoga Mat",
                            Price = 690.00m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Adjustable chrome dumbbell set with storage case",
                            ImageUrl = "/images/dumbbell.jpg",
                            Name = "Dumbbell Set 10kg",
                            Price = 1490.00m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Waterproof double-layer family camping tent for 3-4 persons",
                            ImageUrl = "/images/tent.jpg",
                            Name = "Camping Tent",
                            Price = 2990.00m,
                            Stock = 10
                        });
                });

            modelBuilder.Entity("ProductManagementSystem.Db.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "System Administrator",
                            PasswordHash = "340AACE49FB2DFEBDF5B70CF505213FA:F98DCFC2E00EB1925BC73FCF3AB41889BA66E44CBF317ECDAB2FE618F68C506E",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Standard User",
                            PasswordHash = "AFF486CE5049A27398FB89FCA93F3028:539FAE1CE7948801FFD24A8F3CCA877279AB965265AA0A5288034CB1A0474890",
                            Role = "User",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("ProductManagementSystem.Db.Entities.Product", b =>
                {
                    b.HasOne("ProductManagementSystem.Db.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductManagementSystem.Db.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
