// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagementSystem.Db.Data;

#nullable disable

namespace ProductManagementSystem.Db.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712060005_AddAdvancePropertiesToDb")]
    partial class AddAdvancePropertiesToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductManagementSystem.Db.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Smartphones, Laptops, and Accessories",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kitchenware, TVs, and Home electronics",
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Apparel, Shoes, and Accessories",
                            Name = "Fashion"
                        });
                });

            modelBuilder.Entity("ProductManagementSystem.Db.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Apple iPhone 15 Pro 128GB, Natural Titanium",
                            Name = "iPhone 15 Pro",
                            Price = 35000.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Apple MacBook Air 13-inch M3, 8GB RAM, 256GB SSD",
                            Name = "MacBook Air M3",
                            Price = 42000.00m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Samsung 55-inch Crystal UHD 4K Smart TV",
                            Name = "Smart TV 55\"",
                            Price = 15900.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Automatic Espresso Machine with Milk Frother",
                            Name = "Coffee Maker",
                            Price = 4500.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Lightweight breathable sports shoes for men and women",
                            Name = "Running Shoes",
                            Price = 2200.00m,
                            Stock = 45
                        });
                });

            modelBuilder.Entity("ProductManagementSystem.Db.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "System Administrator",
                            PasswordHash = "340AACE49FB2DFEBDF5B70CF505213FA:F98DCFC2E00EB1925BC73FCF3AB41889BA66E44CBF317ECDAB2FE618F68C506E",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Standard User",
                            PasswordHash = "AFF486CE5049A27398FB89FCA93F3028:539FAE1CE7948801FFD24A8F3CCA877279AB965265AA0A5288034CB1A0474890",
                            Role = "User",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("ProductManagementSystem.Db.Entities.Product", b =>
                {
                    b.HasOne("ProductManagementSystem.Db.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductManagementSystem.Db.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
